version: "3.8"
services:
  uniclique-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uniclique-api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5142:8080"
