// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UniCliqueBackend.Persistence.Contexts;

#nullable disable

namespace UniCliqueBackend.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251101132725_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UniCliqueBackend.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Expiration")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP + interval '30 days'");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 13, 27, 24, 902, DateTimeKind.Utc).AddTicks(9270),
                            Expiration = new DateTime(2025, 12, 1, 13, 27, 24, 902, DateTimeKind.Utc).AddTicks(9270),
                            IsRevoked = false,
                            Token = "sample_refresh_token_admin",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 1, 13, 27, 24, 902, DateTimeKind.Utc).AddTicks(9270),
                            Expiration = new DateTime(2025, 12, 1, 13, 27, 24, 902, DateTimeKind.Utc).AddTicks(9270),
                            IsRevoked = false,
                            Token = "sample_refresh_token_user",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("UniCliqueBackend.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(1995, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 11, 1, 13, 27, 24, 902, DateTimeKind.Utc).AddTicks(9170),
                            Email = "admin@uniclique.com",
                            FullName = "Admin User",
                            IsActive = true,
                            IsBanned = false,
                            PasswordHash = "admin123",
                            PhoneNumber = "5555555555",
                            Role = 2,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(1990, 4, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 11, 1, 13, 27, 24, 902, DateTimeKind.Utc).AddTicks(9180),
                            Email = "business@uniclique.com",
                            FullName = "Business Owner",
                            IsActive = true,
                            IsBanned = false,
                            PasswordHash = "biz123",
                            PhoneNumber = "5551112233",
                            Role = 1,
                            Username = "business1"
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(2000, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 11, 1, 13, 27, 24, 902, DateTimeKind.Utc).AddTicks(9180),
                            Email = "user@uniclique.com",
                            FullName = "Regular User",
                            IsActive = true,
                            IsBanned = false,
                            PasswordHash = "user123",
                            PhoneNumber = "5552223344",
                            Role = 0,
                            Username = "user1"
                        });
                });

            modelBuilder.Entity("UniCliqueBackend.Domain.Entities.UserConsent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AcceptedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ConsentType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAccepted")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ConsentType")
                        .IsUnique();

                    b.ToTable("user_consents", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptedAt = new DateTime(2025, 11, 1, 13, 27, 24, 902, DateTimeKind.Utc).AddTicks(9220),
                            ConsentType = 0,
                            IsAccepted = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AcceptedAt = new DateTime(2025, 11, 1, 13, 27, 24, 902, DateTimeKind.Utc).AddTicks(9220),
                            ConsentType = 1,
                            IsAccepted = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AcceptedAt = new DateTime(2025, 11, 1, 13, 27, 24, 902, DateTimeKind.Utc).AddTicks(9220),
                            ConsentType = 0,
                            IsAccepted = true,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            AcceptedAt = new DateTime(2025, 11, 1, 13, 27, 24, 902, DateTimeKind.Utc).AddTicks(9220),
                            ConsentType = 2,
                            IsAccepted = true,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("UniCliqueBackend.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("UniCliqueBackend.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniCliqueBackend.Domain.Entities.UserConsent", b =>
                {
                    b.HasOne("UniCliqueBackend.Domain.Entities.User", "User")
                        .WithMany("UserConsents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UniCliqueBackend.Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserConsents");
                });
#pragma warning restore 612, 618
        }
    }
}
